version: '3'

services:
    api:
        build: .
        ports:
            - "8081:8081"
            - "8083:8083"
        depends_on:
            - db
        environment: 
            - "DATASTORE=redis"
    db:
        image: redis
        ports:
            - "6379:6379"